# site settings
title: CryptoAdvisor
subtitle: A cryptocurrency investment hedge fund, focusing on ICO's, leveraged trades, and automated exchange arbitrage
email: cryptoadvisor0@gmail.com
description: We are a cryptocurrency investment fund
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 4806 Abbott Ave.
city: Dallas
state: TX
zip_code: 75205
country: United States of America
phone: (214) 770-9226

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
